module.exports = {
  1: [
    "ballpark",
    "big league",
    "bush-league",
    "cleanup hitter",
    "closer",
    "curve",
    "first base",
    "first inning",
    "early innings",
    "ground ball",
    "home run",
    "out of the park",
    "late innings",
    "leadoff hitter",
    "left field",
    "major league",
    "ninth inning",
    "off base",
    "on deck",
    "one base at a time",
    "touch base",
    "singles",
    "swing and miss",
    "pinch hit",
    "pitch a shutout",
    "play ball",
    "relief pitcher",
    "right off the bat",
    "step up to the plate",
    "strike out swinging",
    "strike out looking",
    "switch-hitter"
  ],
  2: [
    "batting 1000",
    "brand new ballgame",
    "brush back",
    "cover one's bases",
    "double header",
    "down to the last out",
    "extra innings",
    "grand slam",
    "grandstanding",
    "hardball",
    "heavy hitter",
    "out of the park",
    "déjà vu",
    "out of left field",
    "screwball",
    "swing for the fences",
    "wheelhouse"
  ],
  3: [
    "beanball",
    "can of corn",
    "Charley horse",
    "ducks on a pond",
    "foot in the bucket",
    "It ain't over till it's over!",
    "cover off the ball",
    "Mendoza line",
    "rally cap",
    "rain-check"
    "whole new ball game",
    "whiff",
    "triple play"
  ]   
};
